kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cimg/android:2026.03
  environment:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    KEYSTORE:
      from_secret: KEYSTORE
    STORE_PASSWORD:
      from_secret: STORE_PASSWORD
    KEY_PASSWORD:
      from_secret: KEY_PASSWORD
  commands:
  - sdkmanager --install "platforms;android-36.1" "build-tools;36.0.0" "platform-tools"
  - yes | sdkmanager --licenses || true
  - ./generate-keystore-config.sh
  - ./gradlew lintRelease assembleRelease --no-daemon --stacktrace

- name: publish
  image: plugins/github-release
  when:
    event:
      - tag
  settings:
    api_key:
      from_secret: github_token
    files: "app/build/outputs/apk/release/*.apk"
